name: cd

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      REGION: europe-west2
      PROJECT_ID: notely-bootdev-494920
      REPO: notely-ar-repo
      IMAGE: notely:latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Auth to Google GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Use gcloud CLI
        run: gcloud info

      - name: Push image to Artifact Registry
        run: |
          gcloud builds submit \
          --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE \
          --region $REGION \
          --allow-unauthenticated \
          --project $PROJECT_ID \
          --max-instances=4
